---
title: "Bare metal analisys"
author: "Gabriel Tavares"
date: "10/19/2022"
output: html_document
---

```{r}
library(tidyverse)
library(patchwork)
library(gt)
library(boot)
library(ggplot2)
library(ggpubr)
library(here)
library(broom)
```

```{r}
source(here("read-input.R"))
source(here("benchmark-plots.R"))
```


```{r}
# ADD NEW INPUTS HERE!

all_gcs <- c("Serial", "Shenandoah", "G1", "Epsilon")
all_heap_sizes <- c("256m1c", "512m1c", "1g1c", "2g2c", "4g2c", "20g1c", "20g2c")
all_functions <- c("graph-bfs", "fibonacci", "factorial", "dynamic-html", "video-processing", "thumbnailer")
day <- "01-02"
n_repetions <- 20
file_name <- "processed-alloc.csv"

experiments_info_alloc <- list()
experiments_info_latency <- list()
experiments_info_gc <- list()

for (gc in all_gcs) {
  for (hs in all_heap_sizes) {
    for (fu in all_functions) {
      index <- length(experiments_info_alloc) + 1
      
      if (!xor(gc != "Epsilon", hs %in% c("20g1c", "20g2c"))) {
        next
      } 
      
      line_alloc <- c(gc, fu, n_repetions, "processed-alloc.csv", day, hs)
      experiments_info_alloc[[index]] <- line_alloc
      
      line_latency <- c(gc, fu, n_repetions, paste("results/", fu, ".csv", sep = ""), day, hs)
      experiments_info_latency[[index]] <- line_latency
      
      line_gc <- c(gc, fu, n_repetions, "processed-gc.csv", day, hs)
      experiments_info_gc[[index]] <- line_gc
    }
  }
}
```


```{r}
df_alloc <- map_df(experiments_info_alloc, function(x) { 
  read_inputs(x[[1]], x[[2]], x[[3]], x[[4]], x[[5]], x[[6]]) %>%
    group_by(gc, heap, cores, run, benchmark) %>%
    mutate(
      alloc = heap_before_mb - lag(heap_after_mb, default = first(heap_before_mb)),
      cumm_alloc = cumsum(alloc),
      ts_s = ts_s - first(ts_s),
      alloc_per_sec = alloc / (ts_s - lag(ts_s))
      ) %>%
    slice(2:n()) %>% # Remove first and last row of each group
    slice(1:(n()-1))
  })

df_gc <- map_df(experiments_info_gc, function(x) { 
  read_inputs(x[[1]], x[[2]], x[[3]], x[[4]], x[[5]], x[[6]])
  })

df_latency <- map_df(experiments_info_latency, function(x) { 
  read_inputs(x[[1]], x[[2]], x[[3]], x[[4]], x[[5]], x[[6]]) %>% 
    add_batch_number() %>%
    mutate(cores = case_when(cores == 1 ~ "single-core", cores == 2 ~ "dual-core")) %>%
    mutate(cores = factor(cores, levels = c("single-core", "dual-core")))
  })
```

# Heavy-slow

In this section we analyze the latency for Heavy-slow functions, like graph-bfs.

```{r, fig.width=10,fig.height=4}
df_heavyslow <- df_latency %>%
  filter(
    batch_number != 0,
    benchmark %in% c("graph-bfs"),
    heap %in% c("4g2c", "20g1c")
  ) %>%
  mutate(
    duration = duration / 1e6
  ) %>%
  group_by(heap, gc) %>%
  mutate(
    p99_lat = quantile(duration, .99),
    median_lat = quantile(duration, .5)
  ) %>% 
  ungroup() %>%
  mutate(
    rel_median_lat = median_lat / min(median_lat),
    rel_p99_lat = p99_lat / min(p99_lat)
  )

ecdf_heavyslow_256m <- df_heavyslow %>%
  ggecdf(x = "duration", color = "gc") %>%
  ggpar(
    xlab = "Response time (ms)",
    ylab = "ECDF",
    xticks.by = 100
  ) +
  grids(linetype = "dashed") +
  geom_vline(data = df_heavyslow, linetype = "dotted", size = 0.8, show.legend = FALSE, aes(colour = gc, xintercept = p99_lat)) +
  geom_vline(data = df_heavyslow, linetype = "dashed", size = 0.5, show.legend = FALSE, aes(colour = gc, xintercept = median_lat)) +
  geom_text(
    data = df_heavyslow, 
    nudge_x = 150, 
    size = 6,
    show_guide = FALSE,
    aes(x = p99_lat, y = 0.2, label = "99th", angle = -90, color = gc)
  ) +
  geom_text(
    data = df_heavyslow, 
    nudge_x = -150,
    size = 6,
    show_guide = FALSE,
    aes(x = median_lat, y = 0.8, label = "Median", angle = -90, color = gc)
  )


table_heavyslow_256m <- df_heavyslow %>%
      distinct(rel_p99_lat, rel_median_lat, gc) %>%
      arrange(rel_p99_lat) %>%
      mutate(
        rel_p99_lat = paste(format(round(rel_p99_lat, 2), nsmall = 2), "x", sep = ""),
        rel_median_lat = paste(format(round(rel_median_lat, 2), nsmall = 2), "x", sep = "")
      ) %>%
      select(gc, rel_median_lat, rel_p99_lat) %>%
      ggtexttable(rows = NULL, theme = ttheme(tbody.style = tbody_style(hjust=1, x=0.9)), cols = c("GC", "Median", "99th")) 


ggarrange(ecdf_heavyslow_256m, table_heavyslow_256m, nrow = 1, widths = c(3, 1))
```

```{r,fig.height=5, fig.width=8}
df_latency %>%
  filter(
    batch_number != 0,
    benchmark %in% c("graph-bfs"),
    gc != "Epsilon"
  ) %>%
  mutate(
    duration = duration / 1e6
  ) %>%
  ggboxplot(x = "heap", y = "duration", color = "gc") %>%
  ggpar (
    xlab = "Heap size / CPU cores",
    ylab = "Latency (ms)"
  ) +
  grids(linetype = "dashed")
```


```{r, fig.width=7,fig.height=4}
df_latency %>% plot_ecdf_latency("graph-bfs", nticks = 50)
```



# Heavy-fast

Functions like the Dynamic-html.

```{r, fig.width=7,fig.height=4}
df_latency %>% plot_ecdf_latency("dynamic-html", nticks = )
```

```{r}
calculate_quantile <- function(df, p = .99) {
  squantile <- \(d, i, ...) d[i,] %>% pull(duration) %>% quantile(p)
  bdf <- boot(data = df, statistic = squantile, R = 4000)
  tidy(bdf, conf.level = .95, conf.int = TRUE) %>% mutate(heap = df$heap[1], gc = df$gc[1], cores = df$cores[1])
}

plot_latency_ic <- function(df) {
  df %>%
    ggplot(aes(y = statistic, x = heap, color = gc)) +
    geom_linerange(aes(ymin = conf.low, ymax = conf.high), position = position_dodge(width = .5)) +
    geom_point(position = position_dodge(width = .5)) +
    theme_minimal() +
    facet_wrap(. ~ cores, scales = "free_x")
}

grouped_dh_latency <- df_latency %>%
  filter(batch_number != 0, benchmark == "dynamic-html") %>%
  mutate(duration = duration / 1e6) %>%
  group_by(gc, heap) %>%
  group_split()


dh_median_ic <- grouped_dh_latency %>% map_df(~calculate_quantile(., p = 0.5))
dh_p95_ic <- grouped_dh_latency %>% map_df(~calculate_quantile(., p = .95))
dh_p99_ic <- grouped_dh_latency %>% map_df(~calculate_quantile(., p = .99))
```

```{r, fig.height=4, fig.width=8}
dh_p99_ic %>% plot_latency_ic()
```

```{r, fig.height=4, fig.width=8}
dh_p95_ic %>% plot_latency_ic()
```


```{r, fig.height=4, fig.width=8}
dh_median_ic %>% plot_latency_ic()
```




```{r,fig.height=5, fig.width=8}
df_latency %>%
  filter(
    batch_number != 0,
    benchmark == "dynamic-html",
    heap %in% all_heap_sizes
    # heap %in% c("256m1c", "512m1c", "1g1c", "20g1c")
    # heap %in% c("2g2c", "4g2c", "20g2c")
  ) %>%
  mutate(
    duration = duration / 1e6
  ) %>%
  ggboxplot(x = "heap", y = "duration", color = "gc") %>%
  ggpar (
    xlab = "Heap size / CPU cores",
    ylab = "Latency (ms)"
  ) %>%
  facet(facet.by = "cores", scales = "free_x") +
  grids(linetype = "dashed") 
```


```{r, fig.width=8,fig.height=6}
df_latency %>%
  plot_ecdf_latency(b = "dynamic-html", c = "gc", heaps = c("1g1c", "20g2c"), gcs = all_gcs, nticks = 10)
```

```{r}
df_latency %>%
  filter(
    batch_number != 0,
    benchmark == "thumbnailer",
    gc %in% c("Epsilon", "Serial"),
    heap %in% c("1g1c", "20g1c")
  ) %>% 
  mutate( duration = duration / 1e6 ) %>%
  gghistogram(x = "duration", color = "gc") +
  xscale("log10")
```


# Light-fast

```{r, fig.width=15, fig.height=6}
p1 <- df_latency %>%
  plot_ecdf_latency(b = "factorial", c = "gc", heaps = c("1g1c", "20g2c"), gcs = all_gcs, nticks = 1000)

p2 <- df_latency %>%
  plot_ecdf_latency(b = "factorial", c = "gc", heaps = c("256m1c", "20g2c"), gcs = all_gcs, nticks = 1000)

ggarrange(p1, p2, nrow = 1)
```




# Minimal


```{r}
df_latency %>%
  filter(
    # batch_number != 0,
    benchmark == "fibonacci", 
    # heap %in% c("20g1c", "20g2c")
    heap %in% c("256m1c", "512m1c"),
    gc == "G1"
  ) %>%
  mutate(
    req_id = as.numeric(as.character(req_id)),
    duration = duration / 1e6
  ) %>%
  ggscatter(x = "req_id", y = "duration", size = 0.5, color = "heap") %>%
  facet(facet.by = "batch_number", nrow = 1)
```


```{r,fig.height=5, fig.width=8}
df_latency %>%
  filter(
    batch_number != 0,
    benchmark == "dynamic-html",
    (heap %in% c("20g1c", "20g2c"))
  ) %>%
  mutate(
    duration = duration / 1e6
  ) %>%
  ggboxplot(x = "heap", y = "duration", color = "gc") %>%
  ggpar (
    xlab = "Heap size / CPU cores",
    ylab = "Latency (ms)"
  ) +
  grids(linetype = "dashed")
```


```{r, fig.width=8,fig.height=6}
df_latency %>%
  plot_ecdf_latency(b = "fibonacci", nticks = 1)
```
